live_config_reload = true

# [env]
# TERM = "xterm-256color"

[window]
# padding.x = 10
# padding.y = 10
# opacity = 0.95
title = "Alacritty"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true
