live_config_reload = true

# [env]
# TERM = "xterm-256color"

[env]
TERM = "alacritty-direct"

[scrolling]
history = 100000

[window]
# padding.x = 10
# padding.y = 10
# opacity = 0.95
title = "Alacritty"
# This disables some keybindings should use the keybiding way
# But could not get it work now
option_as_alt = "Both"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  # { key = "J", mode="Alt", chars="\u006A"}
]
